name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare server
        run: cd server && npm install && sleep 2 && npm uninstall ts-node && sleep 2 && npm install ts-node --save-dev
      - name: Run server
        run: cd server && npx ts-node index.ts && sleep 5
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          working-directory: client
          build: npm run build
          start: npm start && sleep 10
