name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare server
        run: cd server && npm install && sleep 2
      - name: Run server
        run: cd server && ts-node-esm index.ts
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          working-directory: client
          build: npm run build && sleep 5
          start: npm start 
